### ISSUE TITLE
No backslash line continuation...

### ISSUE THREAD

**Issue by Makman2** [coala/coala#558]
Backslashes at EOL to continue code execution is imo bad practice. We should consider using braces then.

**Comment by sils1297** [comment]
So TODO:

- [ ] Make a poll with coala contributors
- [ ] If we want that: add this to codestyle docs
- [ ] grep for backslashes in coala code and remove them

**Comment by AbdealiJK** [comment]
I prefer no backslashes too ... backslashes are irritating

**Comment by sils1297** [comment]
@Makman2 first item done by itself :)

**Comment by AbdealiJK** [comment]
Just came across a case which I didnt know how to do without backslash.
How would you write https://github.com/coala-analyzer/coala/commit/09f114a66dfecebde3c1c6ab529d01a1724fc59e#diff-07b985955ae616d1d2d8e8049abe790cL8 without backslash ?

**Comment by sils1297** [comment]
you put it in brackets

from very.long.package import (
    AModule)

2015-07-05 16:05 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by AbdealiJK** [comment]
Ah right - didnt think of that

**Comment by Makman2** [comment]
so: do we want that?
I'm in favor, so
:+1:

**Comment by sils1297** [comment]
Go ahead, IIRC Abdeali wants it too and we already did some adaptions in
that direction.
Am 12.07.2015 12:34 vorm. schrieb "Makman2" <notifications@github.com>:

**Comment by AbdealiJK** [comment]
What about situations like:

`a_long_variable = from_module.some_class.function_name() or some_other_long_variable_name`

How do I split that into 2 lines ?

**Comment by sils1297** [comment]
brackets :)

**Comment by AbdealiJK** [comment]
how would you put bracket in that ?
```
a_long_variable = (
    from_module.some_class.function_name() or some_other_long_variable_name)
```
is still too long for the 80 char limit

**Comment by sils1297** [comment]
a_long_variable = (from_module.some_class.function_name() or
                          some_other_long_variable_name)

2015-07-12 11:54 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by AbdealiJK** [comment]
ouh. Didnt know that would work. cool

**Comment by Makman2** [comment]
See #751.

**Comment by jayvdb** [comment]
#751 wasnt an enforced rule, it didnt make it to the dev docs.

Problem wasnt solved.

**Comment by jayvdb** [comment]
Actually it is in dev docs at https://api.coala.io/en/latest/Developers/Codestyle.html#line-continuation

But it keeps getting past reviewers.  Need a bear.

https://github.com/coala/coala-bears/issues/2427 is such a bear, otw

**Comment by jayvdb** [comment]
We now have a bear for this.

**Comment by jayvdb** [comment]
This issue reserved for Google Code-in task [4857897759539200](https://codein.withgoogle.com/dashboard/tasks/4857897759539200).

**Comment by Kiy4h** [comment]
I stumbled across [these lines of code](https://github.com/coala/coala/blob/master/coalib/testing/LocalBearTestHelper.py#L97-L103):

```Python
    with prepare_file(lines, filename,
                      force_linebreaks=force_linebreaks,
                      create_tempfile=create_tempfile,
                      tempfile_kwargs=tempfile_kwargs) as (file, fname), \
        execute_bear(local_bear, fname, file, dependency_results=deps_results,
                     **local_bear.get_metadata().filter_parameters(settings)
) as bear_output:
```

And I'm having a trouble removing the backslash.

Anyone can help?
